[profile.default]
solc = "tools/tron-solc/solc-macos-0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
eth_rpc_url = "http://127.0.0.1:8545"

[profile.test]
# Use standard solc for tests
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200

[profile.ci]
# Use standard solc for tests
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
