[profile.default]
solc = "tools/tron-solc/solc-tron-0.8.23"
evm_version = "Shanghai"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]


[profile.test]
# Use standard solc for tests
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200

[profile.ci]
# Use standard solc for tests
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
